package simkit.components;

import simkit.SimEntityBase;
import simkit.random.RandomVariate;

/**
 * Arrival events occur one at a time, with the times between them generated
 * by the RandomVariate interarrivalTimeGenerator.
 * @author ahbuss
 */
public class ArrivalProcess extends SimEntityBase {
    
    private RandomVariate interarrivalTimeGenerator;
    
    protected int numberArrivals;

    /**
     * Instantiate an ArrivalProcess without its interarrivalTimeGenerator set.
     * A call to setInterarrivalTimeGenerator must be made before using.
     */
    public ArrivalProcess() { }
    
    /**
     * Instantiate an ArrivalProcess with the given interarrivalTimeGenerator
     * @param interarrivalTimeGenerator Given RandomVariate to generate interarrival times
     */
    public ArrivalProcess(RandomVariate interarrivalTimeGenerator) {
        this.setInterarrivalTimeGenerator(interarrivalTimeGenerator);
    }
    
    /**
     * initialize numberArrivals to 0
     */
    @Override
    public void reset() {
        super.reset();
        numberArrivals = 0;
    }
    
    /**
     * Schedule first Arrival with delay generated by interarrivalTimeGenerator
     */
    public void doRun() {
        firePropertyChange("numberArrivals", getNumberArrivals());
        
        waitDelay("Arrival", this.interarrivalTimeGenerator);
    }
    
    /**
     * Increment numberArrivals;<br>
     * Schedule next Arrival with delay generated by interarrivalTimeGenerator
     */
    public void doArrival() {
        int oldNumberArrivals = getNumberArrivals();
        this.numberArrivals += 1;
        firePropertyChange("numberArrivals", oldNumberArrivals, getNumberArrivals());
        
        waitDelay("Arrival", this.interarrivalTimeGenerator);
    }
    
    /**
     * @return the interarrivalTimeGenerator
     */
    public RandomVariate getInterarrivalTimeGenerator() {
        return interarrivalTimeGenerator;
    }

    /**
     * @param interarrivalTimeGenerator the interarrivalTimeGenerator to set
     */
    public void setInterarrivalTimeGenerator(RandomVariate interarrivalTimeGenerator) {
        this.interarrivalTimeGenerator = interarrivalTimeGenerator;
    }

    /**
     * @return the numberArrivals
     */
    public int getNumberArrivals() {
        return numberArrivals;
    }

}
